#pragma once

//Application-specific
#define CFLAGS_LIGHT CLONE_FILES|CLONE_IO|CLONE_VM|CLONE_SYSVSEM|CLONE_PARENT|CLONE_SIGHAND
#define CFLAGS_LIGHT2 CLONE_FILES|CLONE_NEWUSER|CLONE_IO|CLONE_VM|CLONE_SYSVSEM|CLONE_PARENT //Missing: CLONE_FS|CLONE_SIGHAND|CLONE_THREAD
#define CFLAGS_THREAD CLONE_FILES|CLONE_FS|CLONE_IO|CLONE_PARENT|CLONE_SIGHAND|CLONE_THREAD|CLONE_VM|CLONE_SYSVSEM
#define CFLAGS_FORK   CLONE_NEWIPC|CLONE_NEWNET|CLONE_NEWNS|CLONE_NEWPID|CLONE_NEWUTS|CLONE_NEWUSER|CLONE_NEWCGROUP
#define STACK_PFLAGS PROT_READ|PROT_WRITE|PROT_EXEC
#define STACK_MFLAGS MAP_ANONYMOUS|MAP_PRIVATE|MAP_POPULATE|MAP_GROWSDOWN|MAP_STACK
#define STACK_MIN 4096 //mmap won't map less than one page (4k)
#define FREE 0
#define LOCKED 1
#define MTX_INIT {0}
#define VA_END 00000111100001111000011110000111100001111000011110000111100001111
#define MAX_THREADS 16

typedef void *(*voidpfp)();
typedef void (*voidfp)();
typedef int (*intfp)();
typedef int (*intfp2)(void*);

//#define syscall(nr, ...) _syscall(nr, ##__VA_ARGS__)
//#define clone(...) syscall(__NR_clone, ##__VA_ARGS__)



